# Generated by Django 5.2.11 on 2026-02-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên hoặc User_ID để nhận diện', max_length=255)),
                ('cookies', models.TextField(help_text='Chuỗi JSON cookie của tài khoản')),
                ('status', models.CharField(choices=[('live', 'Live'), ('die', 'Die')], default='live', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_id', models.CharField(help_text='ID của group hoặc đường dẫn', max_length=100)),
                ('url', models.URLField(help_text='Link dẫn đến group', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShareCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên chiến dịch', max_length=255)),
                ('link_to_share', models.URLField(help_text='Link bài viết hoặc trang web cần share', max_length=1000)),
                ('comment_content', models.TextField(blank=True, help_text='Nội dung sẽ comment vào bài sau khi share', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounts', models.ManyToManyField(related_name='campaigns', to='automation.facebookaccount')),
                ('groups', models.ManyToManyField(related_name='campaigns', to='automation.facebookgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('shared_post_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.facebookaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.sharecampaign')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.facebookgroup')),
            ],
        ),
    ]
