# Generated by Django 5.2.11 on 2026-02-24 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên Fanpage', max_length=255)),
                ('url', models.URLField(help_text='Link đến Fanpage', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(help_text='Link bài viết', max_length=1000, unique=True)),
                ('content_snippet', models.TextField(blank=True, help_text='Một đoạn nội dung bài viết', null=True)),
                ('posted_at', models.DateTimeField(help_text='Thời gian đăng bài ước tính')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('total_engagement', models.IntegerField(default=0, help_text='Tổng lượt tương tác (Like + Cmt + Share)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='automation.observedpage')),
            ],
        ),
    ]
