# Generated by Django 5.2.11 on 2026-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_observedpage_hotpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedpage',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observedpage',
            name='scrape_status',
            field=models.CharField(default='idle', help_text='idle, running, completed, error', max_length=20),
        ),
    ]
