# Generated by Django 5.2.11 on 2026-02-28 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_observedpage_last_scraped_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observedpage',
            name='is_auto_scan',
            field=models.BooleanField(default=False, help_text='Bật để tự động quét 2 lần/ngày bằng Cron'),
        ),
        migrations.AddField(
            model_name='observedpage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharecampaign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotpost',
            name='post_url',
            field=models.URLField(help_text='Link bài viết', max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='hotpost',
            constraint=models.UniqueConstraint(fields=('page', 'post_url'), name='unique_post_per_page'),
        ),
    ]
