# Generated by Django 5.2.11 on 2026-02-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_facebookaccount_user_observedpage_is_auto_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedpage',
            name='auto_scan_time',
            field=models.TimeField(blank=True, help_text='Bỏ trống để chạy mặc định (00:00 & 12:00) hoặc đặt giờ quét cụ thể', null=True),
        ),
    ]
