# Generated by Django 5.2.11 on 2026-03-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_scrapejob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapeJob',
        ),
        migrations.RemoveConstraint(
            model_name='hotpost',
            name='unique_post_per_page',
        ),
        migrations.AddField(
            model_name='hotpost',
            name='video_url',
            field=models.TextField(blank=True, help_text='URL video trong bài viết (nếu có)', null=True),
        ),
        migrations.AddConstraint(
            model_name='hotpost',
            constraint=models.UniqueConstraint(fields=('post_url',), name='unique_post_url'),
        ),
    ]
