# Generated by Django 5.2.11 on 2026-03-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_delete_scrapejob_remove_hotpost_unique_post_per_page_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hotpost',
            constraint=models.UniqueConstraint(fields=('page', 'content_snippet'), name='unique_page_content_snippet'),
        ),
    ]
